import * as fs from 'fs-extra';
import * as path from 'path';

export interface EnvConfig {
  payerPublicKey: string;
  payerKeypairPath: string;
  facilitatorPublicKey: string;
  facilitatorKeypairPath: string;
  facilitatorProgramId: string;
  network: string;
}

export async function createEnvFile(projectPath: string, config: EnvConfig): Promise<void> {
  const envContent = `# x402 Project Configuration
# Generated by xc-setup

# Network Configuration
NETWORK=${config.network}
SOLANA_RPC_URL=https://api.devnet.solana.com

# Keypair Paths
PAYER_KEYPAIR_PATH=${config.payerKeypairPath}
FACILITATOR_KEYPAIR_PATH=${config.facilitatorKeypairPath}

# Public Keys
PAYER_PUBLIC_KEY=${config.payerPublicKey}
FACILITATOR_PUBLIC_KEY=${config.facilitatorPublicKey}

# Program IDs
FACILITATOR_PROGRAM_ID=${config.facilitatorProgramId}

# Test Token (will be added after running 'xc-setup fund')
# TEST_TOKEN_MINT=
`;

  await fs.writeFile(path.join(projectPath, '.env'), envContent);
}

